 import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Roboto({ subsets: ["latin"], weight:"100"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={roboto.className}>
        <nav>
          <ul className="flex gap-6">
            <Link  href='/about'><li>About</li></Link>
            <Link href='/contact'> <li>Contact</li></Link>
            <li><Link href='/blog'>Blog</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
